<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\DCS_MBR_Icon.ico</ApplicationIcon>
    <Version>1.1.5.0</Version>
    <FileVersion>1.1.5.0</FileVersion>
    <AssemblyVersion>1.1.5.0</AssemblyVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GMap.NET.WinPresentation" Version="2.1.7" />
    <PackageReference Include="GMap.NET.Core" Version="2.1.7" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DCSMissionReader.Core\DCSMissionReader.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\DCS_MBR_Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Background\bg001.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\expand_collapse_circle_48dp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="DCS_Search_Guide.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
